version: 2
jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Run commands
          command: |
            echo nice
            echo i am
      - run:
          name: Run multiline
          command: |
            df -h && nproc && free -h && whoami && pwd
            ls -lah
